04 criteria query
anastasiia-fi/book-store pull request #5
Opened 2023-11-02 15:56 UTC by anastasiia-fi

2023-11-04 13:23 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-11-04 13:23 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/controller/BookController.java
> +    public List<BookDto> searchBooks(dto.BookSearchParametersDto searchParameters) {
`dto.BookSearchParametersDto` ?

this is weird :)

should be `BookSearchParametersDto`

2023-11-04 13:23 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/dao/SpecificationBuilder.java
> +@Component
this annotation is redundant on interface

2023-11-04 13:23 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/dto/BookSearchParametersDto.java
> +package dto;
this should not be a separate package - it should be a sub package

2023-11-06 11:39 UTC, liliia-ponomarenko approved these changes
Great 😊

2023-11-06 11:55 UTC, merged