07 security
anastasiia-fi/book-store pull request #8
Opened 2023-11-14 08:20 UTC by anastasiia-fi

2023-11-14 13:02 UTC, yevhenkukharchuk requested changes
Big job! But you should continue for finalize this solution.

2023-11-14 13:02 UTC, yevhenkukharchuk commented on src/main/java/com/example/bookstore/dao/UserRepository.java
you should add also RoleRepository

2023-11-15 14:24 UTC, liliia-ponomarenko approved these changes
Good job! 👏 Let’s  improve your solution ;)

2023-11-15 14:24 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstore/config/SecurityConfig.java
> +@RequiredArgsConstructor
Add annotation EnableMethodSecurity 
Did you test your solution?

2023-11-15 14:24 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstore/config/SecurityConfig.java
> +                                .requestMatchers("/auth/**")
you also should add 
```
"/swagger-ui/**", 
"/errors"
```

2023-11-15 14:24 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstore/controller/AuthController.java
> +
```suggestion
```

2023-11-15 14:24 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstore/dao/RoleRepository.java
> +public interface RoleRepository extends JpaRepository<Role, Long> {
Repository annotation missed

2023-11-15 14:24 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstore/dto/user/UserDto.java
> +public record UserDto(
do you use this Dto?

2023-11-15 14:24 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstore/dto/user/UserRegistrationRequestDto.java
> +@FieldMatch
Let’s add parameters ;)
(message = "Password don`t match",
        field = "password",
        fieldMatch = "verifyPassword")

2023-11-15 14:24 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstore/dto/user/UserRegistrationRequestDto.java
> +        @NotNull
Better use NotBlank with strings

2023-11-15 14:24 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstore/dto/user/UserResponseDto.java
> +        String email
you can return all fields without password

2023-11-15 14:24 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstore/model/User.java
> +    private String shippingAddress;
```suggestion
    private Long id;
    
    @Column(nullable = false, unique = true)
    private String email;
    
    @Column(nullable = false)
    private String password;
    
    @Column(nullable = false)
    private String firstName;
    
    @Column(nullable = false)
    private String lastName;
    private String shippingAddress;
```
Use the same code style for each class

2023-11-15 14:24 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstore/model/User.java
> +    @JoinTable(name = "user_role",
```suggestion
    @JoinTable(name = "users_roles",

```

2023-11-15 14:24 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstore/service/impl/UserServiceImpl.java
> +        user.setRoles(Collections.singleton(roleRepository.findByName(Role.RoleName.ROLE_USER)));
```suggestion
        user.setRoles(Set.of(roleRepository.findByName(Role.RoleName.ROLE_USER)));

```

2023-11-17 14:34 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-11-17 14:34 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/config/SecurityConfig.java
> +                                .requestMatchers(
```suggestion
                                .requestMatchers("/auth/**", "/error", "/swagger-ui/**")

```

2023-11-17 14:34 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/dto/user/UserRegistrationRequestDto.java
> +        @NotBlank
```suggestion
        @NotBlank
        String firstName,
        
        @NotBlank
        String lastName,
        
        String shippingAddress
```

2023-11-17 14:34 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/security/CustomUserDetailsService.java
> +    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String username) {

```

2023-11-17 14:34 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/dao/UserRepository.java
> +    Optional<User> existsByEmail(String email);
```suggestion
    boolean existsByEmail(String email);

```

2023-11-17 14:34 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: varchar(255)
Check all sizes - they should be the same as in requests

2024-02-08 14:50 UTC, merged